[build]
  base = "."
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Use Ubuntu 22.04 LTS build image (this replaces the deprecated Focal image)
[build.processing]
  skip_processing = false